name: Deploy static site (GitHub Pages)

on:
  push:
    branches: [ main ]

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Site quality (non-blocking)
        run: bash bin/site_quality.sh || true

      - name: Prepare publish dir
        run: |
          mkdir -p _site
          rsync -av --delete \
            --exclude='.git/' \
            --exclude='.github/' \
            --exclude='bin/' \
            --exclude='_backups/' \
            . _site/

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: _site

  deploy:
    needs: build
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - id: deployment
        uses: actions/deploy-pages@v4
