name: Prod Smoke
on:
  schedule: [{cron: "*/30 * * * *"}]   # every 30 minutes
  workflow_dispatch:
jobs:
  smoke:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Curl smoke
        run: |
          set -e
          HOST="https://www.rbisintelligence.com"
          routes="/ /main /hdr /hdr/pricing /hdr/what-it-does /main/value /robots.txt /sitemap.xml"
          for p in $routes; do
            code=$(curl -s -o /dev/null -w "%{http_code}" "$HOST$p")
            echo "$p -> $code"
            if [ "$code" -ge 400 ]; then echo "FAIL $p"; exit 1; fi
          done
