name: Site Audit
on:
  push:
    branches: [ main ]
  pull_request:
jobs:
  audit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Link check (lychee)
        uses: lycheeverse/lychee-action@v1
        with:
          args: --verbose --no-progress --exclude-mail --accept 200,206,429 'https://www.rbisintelligence.com/**/*.html' './**/*.html'
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}

      - name: Accessibility (pa11y on key pages)
        run: |
          npm i -g pa11y@6
          pa11y https://www.rbisintelligence.com/ || true
          pa11y https://www.rbisintelligence.com/reports.html || true
          pa11y https://www.rbisintelligence.com/solutions.html || true

      - name: Lighthouse CI (Home + Reports)
        run: |
          npm i -g @lhci/cli@0.13.x
          lhci autorun --collect.url=https://www.rbisintelligence.com/ \
                        --collect.url=https://www.rbisintelligence.com/reports.html \
                        --assert.preset=lighthouse:recommended || true
