name: Site quality

on:
  push:
    branches: [ main ]
  pull_request:
  workflow_dispatch:

jobs:
  quality:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run quality checks (bash)
        run: bash bin/site_quality.sh
